In [ ]:
#Split The String
st="Hi there Sam!"
name=st.split()
print(st)
print(name)

Hi there Sam!
['Hi', 'there', 'Sam!']


In [ ]:
#.format()
name="the diameter of the {planet} is {diameter} kilometer." .format(planet = "Earth" ,diameter="12742")
print(name)

the diameter of the Earth is 12742 kilometer.


In [ ]:
#nest dictionary grab the word "hello"
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}
print(d['k1'][3]["tricky"][3]['target'][3])

hello


In [ ]:
# Create an array of 10 zeros?
import numpy as np
arr=np.zeros(10)
print("An array of 10 zeros:")
print(arr)

An array of 10 zeros:
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [ ]:
# Create an array of 10 fives?
import numpy as np
arr=np.ones(10)*5
print("An array of 10 fives:")
print(arr)

An array of 10 fives:
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


In [ ]:
#Create an array of all the even integers from 20 to 35
import numpy as np
arr=np.arange(20,35,2)
print("Array of all the even integers from 20 to 35")
print(arr) 

Array of all the even integers from 20 to 35
[20 22 24 26 28 30 32 34]


In [ ]:
#Create a 3x3 matrix with values ranging from 0 to 8
import numpy as np
np.arange(0,9).reshape((3,3))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
#Concatenate a and b
import numpy as np
a=np.array([[1,2,3]])
b=np.array([[4,5,6]])
np.concatenate((a, b))

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
#Create a dataframe with 3 rows and 2 columns
import pandas as pd
data = [{'a': 1, 'b': 2},{'a': 10, 'b': 20},{'a': 30, 'b': 31}]
df = pd.DataFrame(data)
df

a   b
0   1   2
1  10  20
2  30  31

In [ ]:
#Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023
import pandas as pd
from datetime import date
start_date = date(2023, 1, 1)
end_date = date(2023, 2, 11)
[date.fromordinal(i) for i in range(start_date.toordinal(), end_date.toordinal())]

[datetime.date(2023, 1, 1),
 datetime.date(2023, 1, 2),
 datetime.date(2023, 1, 3),
 datetime.date(2023, 1, 4),
 datetime.date(2023, 1, 5),
 datetime.date(2023, 1, 6),
 datetime.date(2023, 1, 7),
 datetime.date(2023, 1, 8),
 datetime.date(2023, 1, 9),
 datetime.date(2023, 1, 10),
 datetime.date(2023, 1, 11),
 datetime.date(2023, 1, 12),
 datetime.date(2023, 1, 13),
 datetime.date(2023, 1, 14),
 datetime.date(2023, 1, 15),
 datetime.date(2023, 1, 16),
 datetime.date(2023, 1, 17),
 datetime.date(2023, 1, 18),
 datetime.date(2023, 1, 19),
 datetime.date(2023, 1, 20),
 datetime.date(2023, 1, 21),
 datetime.date(2023, 1, 22),
 datetime.date(2023, 1, 23),
 datetime.date(2023, 1, 24),
 datetime.date(2023, 1, 25),
 datetime.date(2023, 1, 26),
 datetime.date(2023, 1, 27),
 datetime.date(2023, 1, 28),
 datetime.date(2023, 1, 29),
 datetime.date(2023, 1, 30),
 datetime.date(2023, 1, 31),
 datetime.date(2023, 2, 1),
 datetime.date(2023, 2, 2),
 datetime.date(2023, 2, 3),
 datetime.date(2023, 2, 4)

In [ ]:
#Create 2D list to DataFrame
import pandas as pd  
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]
df = pd.DataFrame(lists, columns =['roll','Name', 'Age']) 
print(df )

   roll Name  Age
0     1  aaa   22
1     2  bbb   25
2     3  ccc   24
